export default {
  arrowRight: require('../assets/images/arrow_right.png'),
  about: require('../assets/images/about_school.png'),
  add_child: require('../assets/images/ic_add_child_icon.png'),
  home: require('../assets/images/home.png'),
  timetable: require('../assets/images/timetable.png'),
  calendar: require('../assets/images/ic_calendar_icon.png'),
  noData: require('../assets/images/no_data.png'),
  notifications: require('../assets/images/messages.png'),
  test: require('../assets/images/test.png'),
  take_attendance: require('../assets/images/ic_take_attendacne_dashboard.png'),
  attendance: require('../assets/images/attendance.png'),
  resetPwd: require('../assets/images/reset_pwd.png'),
  logout: require('../assets/images/logout.png'),
  lmdc_logo: require('../assets/images/lmdc_logo.png'),
  lmdc_main_logo: require('../assets/images/lmdc_main_logo.png'),
  yesh_logo: require('../assets/images/yesh_logo.png'),
  yesh_main_logo: require('../assets/images/yesh_main_logo.png'),
  ob_homework: require('../assets/images/onboarding_homework.png'),
  ob_notifications: require('../assets/images/onboarding_notifications.png'),
  ob_timetable: require('../assets/images/onboarding_timetable.png'),
};
