const ActionsType = {
  //Common
  SET_LOADER: 'SET_LOADER',
  SET_FROM_DATE: 'SET_FROM_DATE',
  SET_TO_DATE: 'SET_TO_DATE',

  //Drawer
  SET_ABOUT_US: 'SET_ABOUT_US',
  SET_EVENTS: 'SET_EVENTS',

  //Tabs
  SET_HOME_DASH_STAT: 'SET_HOME_DASH_STAT',
  SET_WEEKLY_TIMETABLE_LIST: 'SET_WEEKLY_TIMETABLE_LIST',
  SET_MONTHLY_TIMETABLE_LIST: 'SET_MONTHLY_TIMETABLE_LIST',
  SET_NOTIFICATIONS_LIST: 'SET_NOTIFICATIONS_LIST',
  SET_NOTIFICATION_DETAIL: 'SET_NOTIFICATION_DETAIL',
  SET_TEACHER_EXAM_ID: 'SET_TEACHER_EXAM_ID',
  SET_TEST_LIST: 'SET_TEST_LIST',
  SET_TEACHER_EXAMS: 'SET_TEACHER_EXAMS',
  SET_TEACHER_EXAM_DETAILS: 'SET_TEACHER_EXAM_DETAILS',
  SET_EXAMS_STUDENTS_DATA: 'SET_EXAMS_STUDENTS_DATA',
  SET_TEST_DETAILS_LIST: 'SET_TEST_DETAILS_LIST',
  SET_ATTENDANCE_LIST: 'SET_ATTENDANCE_LIST',
  SET_USER_ATTENDANCE_ITEM: 'SET_USER_ATTENDANCE_ITEM',
  SET_USER_EXAM_ITEM: 'SET_USER_EXAM_ITEM',
  SET_STUDENTS_LIST: 'SET_STUDENTS_LIST',
  SET_TEACHER_ATTENDANCE_RES: 'SET_TEACHER_ATTENDANCE_RES',
  SET_TEACHER_ATTENDANCE_DETAILS: 'SET_TEACHER_ATTENDANCE_DETAILS',
  SET_ATTENDANCE_SCHEDULED: 'SET_ATTENDANCE_SCHEDULED',
  SET_ATTENDANCE_TEACHERS: 'SET_ATTENDANCE_TEACHERS',
  SET_TEACHER_ATTENDANCE_ID: 'SET_TEACHER_ATTENDANCE_ID',
  SET_ATTENDANCE_DETAILS_LIST: 'SET_ATTENDANCE_DETAILS_LIST',

  //User
  LOGGED_IN: 'LOGGEDIN',
  LOGGED_OUT: 'LOGGEDOUT',
  USERS_LIST: 'USERS_LIST',
  UPDATE_USERS_LIST: 'UPDATE_USERS_LIST',
  CLEAR_USERS_LIST: 'CLEAR_USERS_LIST',
  ACTIVE_LECTURES: 'ACTIVE_LECTURES',
  CURRENT_USER: 'CURRENT_USER',
  USER_TYPE: 'USER_TYPE',
};

export default ActionsType;
